apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  selector:
    matchLabels:
      component: queue
  template:
    metadata:
      labels:
        component: queue
    spec:
      containers:
        - name: queue
          image: fedehermida/queue
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE
              value: queue
