version: '3.7'

services:
  raft-node:
    build:
      context: .
      args:
        SERVICE: raft-node
      target: development
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - './apps/raft-node:/workspace/apps/raft-node'
      - './libs:/workspace/libs'
      - './node_modules:/workspace/node_modules'
    command: npm run start:service raft-node
    environment:
      - ENVIRONMENT=docker
    networks:
      - iasc-api-network
      - raft-network
    deploy:
      replicas: 3

  raft-pub-sub:
    image: redis:alpine
    networks:
      - raft-network

  bids:
    container_name: bids
    build:
      context: .
      args:
        SERVICE: bids
      target: development
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - './apps/bids:/workspace/apps/bids'
      - './libs:/workspace/libs'
      - './node_modules:/workspace/node_modules'
    command: npm run start:service bids
    ports:
      - 6003:3000
      - 20000:9229
    env_file: ${BIDS_ENV}
    environment:
      - ENVIRONMENT=docker
    networks:
      - iasc-api-network

  event:
    container_name: event
    build:
      context: .
      args:
        SERVICE: event
      target: development
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - './apps/event:/workspace/apps/event'
      - './libs:/workspace/libs'
      - './node_modules:/workspace/node_modules'
    command: npm run start:service event
    ports:
      - 6005:3000
      - 20004:9229
    env_file: ${EVENT_ENV}
    environment:
      - ENVIRONMENT=docker
    networks:
      - iasc-api-network

  repository:
    container_name: repository
    build:
      context: .
      args:
        SERVICE: repository
      target: development
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - './apps/repository:/workspace/apps/repository'
      - './libs:/workspace/libs'
      - './node_modules:/workspace/node_modules'
    command: npm run start:service repository
    ports:
      - 6006:3000
      - 20005:9229
    env_file: ${REPOSITORY_ENV}
    environment:
      - ENVIRONMENT=docker
    networks:
      - iasc-api-network

  rabbitmq:
    image: rabbitmq:3.10.6-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - iasc-api-network

networks:
  iasc-api-network:
    driver: bridge
  raft-network: