apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: event-deployment
spec:
 behavior:
  scaleDown:
   stabilizationWindowSeconds: 60
   policies:
   - type: Pods
     value: 10
     periodSeconds: 15
  scaleUp:
   stabilizationWindowSeconds: 0
   policies:
   - type: Pods
     value: 10
     periodSeconds: 15
   selectPolicy: Max
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: event-deployment
 minReplicas: 1
 maxReplicas: 10

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: event-deployment
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: event-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 10