apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
spec:
  selector:
    matchLabels:
      component: event
  replicas: 1
  template:
    metadata:
      labels:
        component: event
    spec:
      containers:
        - name: event
          image: fedehermida/event
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE
              value: event
            - name: RABBITMQ_URL
              value: rabbitmq:5672
            - name: BIDS_URL
              value: bids-cluster-ip-service:3000
            - name: REPOSITORY_URL
              value: repository-cluster-ip-service:3000
          resources:
            limits:
              cpu: 0.5
            requests:
              cpu: 0.5
