apiVersion: apps/v1
kind: Deployment
metadata:
  name: bids-deployment
spec:
  selector:
    matchLabels:
      component: bids
  replicas: 1
  template:
    metadata:
      labels:
        component: bids
    spec:
      containers:
        - name: bids
          image: fedehermida/bids
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE
              value: bids
            - name: EVENT_URL
              value: event-cluster-ip-service:3000
            - name: RABBITMQ_URL
              value: rabbitmq:5672
          resources:
            limits:
              cpu: 0.5
            requests:
              cpu: 0.5
