apiVersion: apps/v1
kind: Deployment
metadata:
  name: repository-deployment
spec:
  selector:
    matchLabels:
      component: repository
  replicas: 5
  template:
    metadata:
      labels:
        component: repository
    spec:
      containers:
        - name: repository
          image: fedehermida/repository
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE
              value: repository
            - name: RABBITMQ_URL
              value: rabbitmq:5672
            - name: EVENT_URL
              value: event-cluster-ip-service:3000
            - name: BIDS_URL
              value: bids-cluster-ip-service:3000
            - name: REDIS_HOST
              value: redis-cluster-ip-service
